[project]
name = "mcp-full-name-demo"
version = "0.1.0"
description = "mcp-full-name-demo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.45.1",
    "argparse>=1.4.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.2.1",
    "python-dotenv>=1.0.1",
]
